In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
# Optional:
# from xgboost import XGBRegressor

In [2]:
df = pd.read_csv("SeoulBikeData.csv", encoding='unicode_escape')  # replace with your actual CSV

# Extract datetime features
df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)

In [3]:

df['day'] = df['Date'].dt.dayofweek
df['month'] = df['Date'].dt.month

# Optional: drop original datetime if not needed
df = df.drop(columns=['Date'])

# Define target and features
y = df['Rented Bike Count']
X = df.drop(columns=['Rented Bike Count'])

In [4]:
df.head()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,day,month
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Rented Bike Count          8760 non-null   int64
 1   Hour                       8760 non-null   int64
 2   Temperature(°C)            8760 non-null   float64
 3   Humidity(%)                8760 non-null   int64
 4   Wind speed (m/s)           8760 non-null   float64
 5   Visibility (10m)           8760 non-null   int64
 6   Dew point temperature(°C)  8760 non-null   float64
 7   Solar Radiation (MJ/m2)    8760 non-null   float64
 8   Rainfall(mm)               8760 non-null   float64
 9   Snowfall (cm)              8760 non-null   float64
 10  Seasons                    8760 non-null   object
 11  Holiday                    8760 non-null   object
 12  Functioning Day            8760 non-null   object
 13  day                        8760 non-null   int32
 14  month                      8760 non-null   int32
dtypes: float64(6), int32(2), int64(4), object(3)
memory usage: 958.2+ KB

In [6]:
categorical_features = ['Seasons', 'Holiday', 'Functioning Day', 'month', 'Hour', 'day']
numerical_features = ['Temperature(°C)', 'Wind speed (m/s)', 'Humidity(%)', 'Visibility (10m)','Dew point temperature(°C)',
                      'Solar Radiation (MJ/m2)','Rainfall(mm)','Snowfall (cm)']  # adjust based on your dataset

In [7]:
# Encoding for categorical
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Scaling for numerical
numerical_transformer = StandardScaler()

# Combine them in a ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

In [8]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Temperature(°C)', 'Wind speed (m/s)',
                                  'Humidity(%)', 'Visibility (10m)',
                                  'Dew point temperature(°C)',
                                  'Solar Radiation (MJ/m2)', 'Rainfall(mm)',
                                  'Snowfall (cm)']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Seasons', 'Holiday', 'Functioning Day',
                                  'month', 'Hour', 'day'])])

In [44]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model1=LinearRegression()

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', model1)
])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

In [46]:
# Evaluation
rmse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

RMSE: 123605.00
R² Score: 0.70

In [13]:
y_pred[1:9]

array([ 724.5 ,  676.74, 2273.28,  593.24,  758.16, 1758.26,  621.65,
        829.87])

In [14]:
X.head()

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,day,month
0,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
1,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
2,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
3,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12
4,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes,4,12

In [27]:
y.head()

0    254
1    204
2    173
3    107
4     78
Name: Rented Bike Count, dtype: int64

In [15]:
X_test.head()

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,day,month
6056,8,27.2,69,1.8,1999,21.0,0.70,0.0,0.0,Summer,No Holiday,Yes,4,8
5556,12,32.6,51,2.1,800,21.1,3.21,0.0,0.0,Summer,No Holiday,Yes,4,7
5990,14,34.0,50,1.2,1744,22.1,1.68,0.0,0.0,Summer,No Holiday,Yes,1,8
7674,18,16.9,47,1.4,1637,5.5,0.11,0.0,0.0,Autumn,No Holiday,Yes,1,10
3319,7,6.4,51,1.0,1398,-3.0,0.19,0.0,0.0,Spring,No Holiday,Yes,2,4

In [43]:
y_test.head()

6056    1728
5556     822
5990     658
7674    2716
3319    1083
Name: Rented Bike Count, dtype: int64

In [51]:
sample=[[0	,-5.2	,37,	2.2,	2000,	-17.6,	0.0,	0.0,	0.0,	'Winter',	'No Holiday'	,'Yes',	4,	12]]
sample1=[[14,	34.0,	50,	1.2,	1744,	22.1,	1.68,	0.0,	0.0,	'Summer',	'No Holiday'	,'Yes',	1,	8]]

In [52]:
c=pd.DataFrame(sample1
    ,columns=['Hour',	'Temperature(°C)',	'Humidity(%)',	'Wind speed (m/s)',
                    	'Visibility (10m)',	'Dew point temperature(°C)',	'Solar Radiation (MJ/m2)',
                            	'Rainfall(mm)',	'Snowfall (cm)',	'Seasons',	'Holiday',	'Functioning Day',
                                    	'day',	'month'])

In [39]:
c

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,day,month
0,1,20,37,2.2,2000,5,0.0,0.0,0.0,Summer,No Holiday,Yes,4,12

In [53]:
predicted=pipeline.predict(c)

In [54]:
predicted

array([982.62227064])